### ISSUE TITLE
Add horrorshow, maud and Zapper

### ISSUE THREAD

**Issue by lnicola** [djc/template-benchmarks-rs#1]
https://github.com/Stebalien/horrorshow-rs
https://github.com/lfairy/maud
https://ceres1.space/posts/zapper/

**Comment by damody** [comment]
zapper is not enough to work benchmark's functional.
maud is not in stable rust.

**Comment by lnicola** [comment]
Yeah, and `maud` seems to break pretty often. Maybe it's worth closing this for now?

**Comment by djc** [comment]
Thanks for looking this!
