### ISSUE TITLE
Update with Handlebars 3.0

### ISSUE THREAD

**Issue by batisteo** [djc/template-benchmarks-rs#24]
Handlebars come with some performance optimisations. We’d like to see them in the benchmarks!

https://www.reddit.com/r/rust/comments/et4qrz/ann_handlebars_30_with_performance_boost/

**Comment by djc** [comment]
I've updated the results in c7e97b409ee40ff1f118d4cadc29e698d4a0efb4. Thanks for the ping!

**Comment by batisteo** [comment]
Dankjewel! You rock :muscle:
