### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Kogia-sima** [djc/template-benchmarks-rs#26]
Why don't you specify the license ?

**Comment by djc** [comment]
Hasn't seemed especially important so far. What's your use case?

**Comment by Kogia-sima** [comment]
Are you aware of this?

https://choosealicense.com/no-permission/

Legally, without a license, no one can use your code.

I want to measure the performance of [this crate](https://github.com/Kogia-sima/sailfish) and paste the result on my repository. However, since this repository doesn't specify license, I have to write a benchmark code from scratch. It is a waste of time.

**Comment by djc** [comment]
You have my express permission to reuse the benchmarks in this repository for the purpose of benchmarking your implementation, provided you state proper attribution.

If sailfish works on stable Rust, I'd also be happy to add benchmarks for it to this repository.

**Comment by Kogia-sima** [comment]
> You have my express permission to reuse the benchmarks in this repository for the purpose of benchmarking your implementation, provided you state proper attribution.

Thank you for granting permission! I'll send a PR after I add a benchmark in my repository.
