### ISSUE TITLE
Add ructe

### ISSUE THREAD

**Issue by lnicola** [djc/template-benchmarks-rs#5]
https://github.com/kaj/ructe

**Comment by bhansconnect** [comment]
I created a [pull request](https://github.com/djc/template-benchmarks-rs/pull/7) that adds ructe support.

**Comment by djc** [comment]
This has been merged, thanks!

**Comment by lnicola** [comment]
It's still missing from the list in the README.

**Comment by djc** [comment]
Not anymore. 👍
