### ISSUE TITLE
Add yarte

### ISSUE THREAD

**Issue by thanet-s** [djc/template-benchmarks-rs#73]
Add [yarte](https://github.com/botika/yarte) please.

**Comment by djc** [comment]
I've had some discussions with the author of yarte in the past, and while I can't find a public reference to it now, I'm pretty sure he wanted yarte to be removed from this benchmark.

**Comment by djc** [comment]
Looking at the commit history, I guess I removed the issue (if I recall correctly, because the yarte author wasn't very friendly).

**Comment by thanet-s** [comment]
Oh so sad to hear that.
