### ISSUE TITLE
Maud Support

### ISSUE THREAD

**Issue by bhansconnect** [djc/template-benchmarks-rs#8]
I feel like [maud](https://github.com/lfairy/maud) is the last major rust templating library that should be added to this benchmark. Sadly, I can't seem to get the other benchmarks to compile happily with maud.

```
#![feature(proc_macro_non_items)]
#![feature(use_extern_macros)]
```

seems to be the root of the issues. I am gonna keep looking into it, but if anyone else wants to try, that would be greatly appreciated.

**Comment by IronOxidizer** [comment]
@djc [Maud now works in stable as of September 27](https://github.com/lambda-fairy/maud/pull/219). Maybe it's worth adding it as well as updated the other benchmarks (also add sailfish to the top of README, it's currently missing).

**Comment by djc** [comment]
I'm happy to accept it if someone updates/redoes the PR for it, but I probably won't spend time on updating it myself.

**Comment by Th3Whit3Wolf** [comment]
Maud has been added to the benchmarks. This can be closed now.
